# OPTIONAL
# used to scrape exposed metrics (i.e. of delivery-service)
# usage requires:
# - removal of comment for entry "ocm_gear.prometheus" in "configs.yaml"

internal:

  # scrapeInterval (optional)
  scapeInterval: 15s

  # ingress (optional)
  ingress:

    # annotations (optional)
    # annotations to be passed to the ingress resource
    annotations: {}

    # class (optional)
    # ingress class used for the annotation "kubernetes.io/ingress.class", e.g. "nginx"
    class: nginx

    # hosts
    # (internal and external) hostnames of the prometheus instance
    hosts:
    - ...

    # tls_host_names
    # list of hostnames tls should be configured for
    tls_host_names:
    - ...
