#!/usr/bin/env bash
set -e

# usage: $1: <src-dir>

src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"

error=0

files="$src_dir/.ci/*"
excluded_files=".ci/lint,.ci/lint-flake8,.ci/pipeline_definitions"

# flake8 / the linter it instruments cannot handle our special type-hints (CliHint)
if flake8 --max-line-length=101 --select=E101,E117,E201,E202,E203,E225,E251,E3,E4,E5,E703,E9,W1,W2,W3,W6,F --count --format=pylint --ignore=F722,F821 --exclude=$excluded_files $files; then
    echo "flake8 succeeded"
else
    echo "flake8 found errors (see above)"
    ((error|=1))
fi

if [ $error -eq 0 ]; then
    exit 0
elif [ $error -gt 0 ]; then
    exit 1
fi
