#!/usr/bin/env python3

import argparse
import logging
import os

import ccc.oci
import ci.log
import ci.util
import cnudie.retrieve
import ctt.process_dependencies
import ocm
import version as version_mod


ci.log.configure_default_logging()
logger = logging.getLogger(__name__)

own_dir = os.path.abspath(os.path.dirname(__file__))
repo_root = os.path.abspath(os.path.join(own_dir, os.pardir))


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--component-descriptor-path',
        required=False,
        help='Path to the component descriptor YAML file.',
    )
    return parser.parse_args()


def ocm_gear_version() -> str:
    effective_version = os.environ.get('EFFECTIVE_VERSION')

    if effective_version and version_mod.is_final(effective_version):
        return effective_version

    version_file = os.path.join(repo_root, 'VERSION')
    with open(version_file, 'r') as file:
        version = file.read().strip()

    parsed_version = version_mod.parse_to_semver(version)
    parsed_version = parsed_version.replace(prerelease=None)

    if parsed_version.patch:
        parsed_version = parsed_version.replace(patch=parsed_version.patch - 1)
    elif parsed_version.minor:
        parsed_version = parsed_version.replace(minor=parsed_version.minor - 1)
    elif parsed_version.major:
        parsed_version = parsed_version.replace(major=parsed_version.major - 1)

    return str(parsed_version)


def main():
    args = parse_args()

    source_repo = 'europe-docker.pkg.dev/gardener-project/releases'
    tgt_ocm_repo_path = 'releases/odg'

    oci_client = ccc.oci.oci_client()

    lookup = cnudie.retrieve.create_default_component_descriptor_lookup(
        ocm_repository_lookup=cnudie.retrieve.ocm_repository_lookup(source_repo),
        oci_client=oci_client,
    )

    if component_descriptor_path := args.component_descriptor_path:
        component_descriptor = ocm.ComponentDescriptor.from_dict(
            component_descriptor_dict=ci.util.parse_yaml_file(component_descriptor_path),
        )
    else:
        component_descriptor = lookup(ocm.ComponentIdentity(
            name='ocm.software/ocm-gear',
            version=ocm_gear_version(),
        ))

    tuple(
        ctt.process_dependencies.process_images(
            processing_cfg_path=os.path.join(repo_root, 'processing.cfg'),
            root_component_descriptor=component_descriptor,
            component_descriptor_lookup=lookup,
            inject_ocm_coordinates_into_oci_manifests=True,
            oci_client=oci_client,
            tgt_ocm_repo_path=tgt_ocm_repo_path,
        )
    )

    logger.info('Image replication completed.')


if __name__ == '__main__':
    main()
