#!/usr/bin/env python3

import os

import ci.util


repo_dir = os.path.abspath(ci.util.check_env('MAIN_REPO_DIR'))
dependency_name = ci.util.check_env('DEPENDENCY_NAME')
dependency_version = ci.util.check_env('DEPENDENCY_VERSION')

delivery_service_versionfile = os.path.join(repo_dir, 'DELIVERY_SERVICE_VERSION')
delivery_dashboard_versionfile = os.path.join(repo_dir, 'DELIVERY_DASHBOARD_VERSION')
delivery_db_versionfile = os.path.join(repo_dir, 'DELIVERY_DB_VERSION')


def write_component_version_to_file(file_path: str):
    with open(file_path, 'w') as version_file:
        version_file.write(dependency_version.strip())


def main():
    if dependency_name == 'ocm.software/ocm-gear/delivery-service':
        write_component_version_to_file(delivery_service_versionfile)
    elif dependency_name == 'ocm.software/ocm-gear/delivery-dashboard':
        write_component_version_to_file(delivery_dashboard_versionfile)
    elif dependency_name == 'ocm.software/ocm-gear/delivery-db':
        write_component_version_to_file(delivery_db_versionfile)
    else:
        raise RuntimeError(f"Don't know how to upgrade dependency: {dependency_name}")


if __name__ == '__main__':
    main()
